version: '3.8'
services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: unchaptrd_finance
    ports:
      - "5433:5432"
    volumes:
      - unchaptrd_postgres_data:/var/lib/postgresql/data

volumes:
  unchaptrd_postgres_data:
